version: '3.1'
services:
  database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    volumes:
      - db-volume:/var/lib/postgresql/data # persist data even if container shuts down
    ports:
      - "15432:5432"
volumes:
  db-volume: # named volumes can be managed easier using docker-compose
